### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by Shynixn** [lukasbindreiter/white-brush#12]
"Erstellen sie einen Projektabschlussbericht der auf ca. 8-10
Seiten mindestens folgendes enthält:
‣Team und Thema (Titelblatt ist nicht notwendig)
‣Projektbeschreibung
‣Überblick über ihre Entwicklung (Diagramme, Screenshots, etc)
‣Beschreibung der realisierten Funktionen gerne in technischen Details
‣Mind. drei Quellen / Links die ihre Kollegen als Startpunkte für ähnliche
Projekte verwenden können"

**Comment by lukasbindreiter** [comment]
Einige Quellen:

- http://scikit-image.org/docs/dev/auto_examples/segmentation/plot_niblack_sauvola.html
- https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_imgproc/py_morphological_ops/py_morphological_ops.html
- https://docs.opencv.org/3.4/d4/d73/tutorial_py_contours_begin.html
- http://www.aishack.in/tutorials/sudoku-grabber-opencv-detection/

**Comment by Shynixn** [comment]
Add diagrams. 👍
