### ISSUE TITLE
Create method to convert colors from different formats to a RGB tuple

### ISSUE THREAD

**Issue by lukasbindreiter** [lukasbindreiter/white-brush#26]
Via the CLI the user should be able to specify colors either by hex code or by name
What we need is a method parse_color, which works like this:
```python
>>> parse_color("#ff0000")
(255, 0, 0)
>>> parse_color("Red") # should be case insensitive
(255, 0, 0)
```

The [webcolor](https://pypi.org/project/webcolors/) project already contains functionality to convert color names to rgb values and also to parse hex color codes, so the easiest approach would probably be to integrate that.

parse_color should probably be best placed in a new `utils.py` module in `white_brush.colors`

**Comment by Shynixn** [comment]
Added, supports the following options:
- #729976
- rEd
- 231,115,70
